name = "remix-cf-template"
pages_build_output_dir = "build/client"
compatibility_date = "2024-02-11"
kv_namespaces = [
  { binding = "cache", id = "d264ce27290743f98f74615eb733587e" }
]

[vars]
GITHUB_OWNER = "beeman"
GITHUB_REPO = "remix-cf-template"
